#!/usr/bin/env bash

# Unofficial Strict Mode
set -euo pipefail
IFS=$'\n\t'

# User-defined Variables
ARCH_TYPES=('arm' 'arm64' 'x86' 'x64')
ARCH=${ARCH_TYPES[0]}
BROMITE_GIT_URL_UPSTREAM="https://github.com/bromite/bromite.git"
BROMITE_GIT_URL=${BROMITE_GIT_URL_UPSTREAM:-}
BROMITE_GIT_TAGS=
GN_ARGS=
OUTPUT_DIR=
PATCHES_DIR=
NAME=
NO_BROMITE_PATCHES=
NO_SKIP_PATCHES=
REVISION=
TARGET_TYPES=(
    'chrome_public_apk'
    'system_webview_apk')
TARGET=${TARGET_TYPES[0]}
UBUNTU_INSTALL_BUILD_DEPS=
UPSTREAM=
UPSTREAM_SHORT_HASH=

# Options
opts=(
    "-a, --arch=<arch> | Where <arch> is: $(echo "${ARCH_TYPES[@]}" \
        | sed -E "s/\s/, /g"). Defaults to $ARCH"
    "-b, --bromite-git-url=<url> | Where <url> is a Bromite Git repository. Defaults to $BROMITE_GIT_URL_UPSTREAM"
    "-g, --gn-args=<args> | Where <args> is a string of GN build arguments"
    "-o, --output-dir=<dir> | Where <dir> is a path to save the APK. Defaults to ./out"
    "-p, --patches-dir=<dir> | Where <dir> is a path to a directory containing custom patches"
    "-t, --target=<target> | Where Ninja <target> is: $(echo "${TARGET_TYPES[@]}" \
        | sed -E "s/\s/, /g"). Defaults to $TARGET"
    "-r, --revision=<revision> | Where <revision> is a Bromite release tag. Defaults to latest release"
    "-u, --upstream=<commit-hash:=master> | Where <commit-hash> is a long-format git commit. Defaults to master's HEAD. When set, any Chromium tag can be assigned to <revision>"
    "--no-bromite-patches | Only apply patches from Bromite's chromium_patches_list.txt"
    "--no-skip-patches | Exit on failed patch attempts"
    "--dark-navbar | Prefer a dark navigation bar over a white one"
    "--ubuntu-install-build-deps | Run Chromium's build/install-build-deps-android.sh during fetch-sync"
    "-h, --help | Print help menu")

# Constants
DEFAULTS=('set-revision' 'fetch-sync' 'prepare' 'build')
CWD=$(cd "$( dirname "$0" )" && pwd)
BUILD_DIR=$CWD/build

# ENV
PYTHONPATH=${PYTHONPATH:-}

clean () {
    rm -rf "$BUILD_DIR/chromium/src/out"
}

set-revision () {
    local custom_build
    local chromium_archive
    local error_msg=

    BROMITE_GIT_TAGS=$(git ls-remote --tags --sort="v:refname" $BROMITE_GIT_URL)

    custom_build=$([[ $UPSTREAM ]] && [[ $REVISION ]] \
        && echo 1 \
        || echo '')

    [[ $custom_build ]] \
        && chromium_archive="https://github.com/chromium/chromium/archive/$REVISION.tar.gz" \
        && [[ $(curl -Lso /dev/null -I -w "%{http_code}" "$chromium_archive") != 200 ]] \
        && error_msg="Error: Release tag $REVISION not found"

    [[ ! $custom_build ]] && [[ $REVISION ]] \
        && [[ ! $(echo "$BROMITE_GIT_TAGS" | grep "$REVISION") ]] \
        && error_msg="Error: Release tag $REVISION not found"

    [[ ! $custom_build ]] && [[ ! $REVISION ]] \
        && REVISION=$(echo "$BROMITE_GIT_TAGS"  \
            | tail --line=1 \
            | cut --delimiter='/' --fields=3)

    [[ ! $custom_build ]] && [[ ! $REVISION ]] \
        && error_msg="A Bromite release couldn't be found. Check your network and try again"

    [[ $UPSTREAM ]] \
        && UPSTREAM_SHORT_HASH=$(echo $([[ $UPSTREAM != master ]] \
                && echo $UPSTREAM \
                || git ls-remote "$BROMITE_GIT_URL" HEAD \
                    | awk '{print $1}') \
            | sed -E "s/^(.{7}).+/\1/")

    [[ $error_msg ]] \
        && echo "$error_msg" \
        && exit 1

    [[ $UPSTREAM_SHORT_HASH ]] \
        && echo "Using Bromite git commit $UPSTREAM_SHORT_HASH"

    echo "Revision now set to $REVISION"
}

fetch-sync () {
    local hash
    local bromite_dir

    mkdir -p "$BUILD_DIR"
    cd "$BUILD_DIR"

    #bromite_dir=$([[ $UPSTREAM_SHORT_HASH ]] \
    #    && echo "bromite-$UPSTREAM_SHORT_HASH" \
    #    || echo "bromite-$REVISION")

    #rm -rf "$bromite_dir"

    #echo "Fetching Bromite"
    #git clone $BROMITE_GIT_URL "$bromite_dir" -q

    #hash=$([[ $UPSTREAM ]] \
    #    && echo "$UPSTREAM" \
    #    || echo "$BROMITE_GIT_TAGS" \
    #        | grep "$REVISION" \
    #        | awk '{print $1}')

    #cd "$bromite_dir"
    #git reset "$hash" --hard -q
    #rm -rf .git

    # Fetch & Sync Chromium
    echo "Fetching and Syncing Chromium"

    #cd "$BUILD_DIR"

    #mkdir -p chromium
    cd chromium

    # Partial checkouts not supported, delete and start over (crbug.com/230691)
    #[[ ! -e .gclient ]] || [[ ! -e .gclient_entries ]] || [[ ! -d .cipd ]] \
    #    && rm -rf ../chromium/{*,.g*,.c*} \
    #    && fetch --nohooks --no-history android

    # Use custom debloated gclient config
    #cp -f "$CWD/.gclientconfig" .gclient

    # Enter chromium src root
    cd src

    # If "apt-get" command detected, use install-build-deps to bootstrap env
    # Also ensure jdk is installed, rather than depend on third_party/jdk
    # Requires root privileges and --ubuntu-install-build-deps flag
    #[[ $(command -v apt-get) ]] \
    #    && [[ $UBUNTU_INSTALL_BUILD_DEPS ]] \
    #    && sudo ./build/install-build-deps-android.sh \
    #    && sudo apt-get -qq install default-jdk

    # Reset tree
    #git clean -fdxq --exclude="out/Default_${REVISION}"

    #echo 'y' | gclient sync --no-history -r "$REVISION"
}

prepare () {
    local bromite_dir
    local bromite_src

    local patchlist_path
    local patchlist
    local patch_status

    bromite_dir=$([[ $UPSTREAM_SHORT_HASH ]] \
        && echo "$BUILD_DIR/bromite-$UPSTREAM_SHORT_HASH" \
        || echo "$BUILD_DIR/bromite-$REVISION")

    [[ ! -d $BUILD_DIR/chromium/src ]] || [[ ! -d $bromite_dir ]] \
        && fetch-sync

    bromite_src=$([[ -d "$bromite_dir/build" ]] \
        && echo "$bromite_dir/build" \
        || echo "$bromite_dir")

    patchlist_path=$([[ $NO_BROMITE_PATCHES ]] \
        && echo "$bromite_src/chromium_patches_list.txt" \
        || echo "$bromite_src/cromite_patches_list.txt")

    # Prep Patching
    rm -rf "$BUILD_DIR/patches"

    cp -rf "$bromite_src/patches" \
        "$BUILD_DIR/patches"

    [[ $PATCHES_DIR ]] && [[ -d $PATCHES_DIR ]] \
        && cp -rf "$PATCHES_DIR/." \
            "$BUILD_DIR/patches"

    cd "$BUILD_DIR/chromium/src"

    # Patch List Order
    [[ -e $patchlist_path ]] \
        && patchlist=($(sed -e "/^$/d" -e "s|^|$BUILD_DIR/patches/|g" \
            < "$patchlist_path")) \
        || patchlist=("$BUILD_DIR"/patches/*.patch)

    # Add custom patches to patchlist
    if [[ $PATCHES_DIR ]] && [[ -d $PATCHES_DIR ]]; then
        for patchfile in "$PATCHES_DIR"/*.patch; do
            [[ ! -e "$bromite_src/patches/$(basename "$patchfile")" ]] \
                && patchlist+=("$patchfile")
        done
    fi

    # Apply Patches
    for patchfile in "${patchlist[@]}"; do
        patch_status=$(git apply --whitespace=nowarn --check "$patchfile" \
            &>/dev/null; \
            echo $?)

        [[ $patch_status -gt 0 ]] \
            && [[ ! $NO_SKIP_PATCHES ]] \
            && echo "Skipping, doesn't apply: $(basename "$patchfile")" \
            && continue

        echo "Applying patch: $(basename "$patchfile")"
        git apply --whitespace=nowarn "$patchfile"
    done
}

build () {
    local bromite_dir
    local bromite_src
    local bromite_gn

    local gn_args_bromite
    local gn_args_user_arr
    local gn_args

    local output_apk_basename
    local apk_basename

    [[ ! -d $BUILD_DIR/chromium/src ]] \
        && fetch-sync \
        && prepare


    # V8 Compiler Optimization Workaround | https://crbug.com/942497
    #sed -i 's|"-O0"|"-O2"|g' \
    #    "$BUILD_DIR/chromium/src/build/config/compiler/BUILD.gn"

    bromite_dir=$([[ $UPSTREAM_SHORT_HASH ]] \
        && echo "$BUILD_DIR/bromite-$UPSTREAM_SHORT_HASH" \
        || echo "$BUILD_DIR/bromite-$REVISION")

    bromite_src=$([[ -d "$bromite_dir/build" ]] \
        && echo "$bromite_dir/build" \
        || echo "$bromite_dir")

    cd "$BUILD_DIR/chromium/src"
    export CHROMIUM_OUTPUT_DIR="out/Default_${REVISION}"
    mkdir -p "$CHROMIUM_OUTPUT_DIR"

    # Build
    gn gen --args="target_os = \"android\" $(cat $bromite_src/cromite.gn_args) target_cpu = \"arm64\" " $CHROMIUM_OUTPUT_DIR
    autoninja -C "$CHROMIUM_OUTPUT_DIR" ${TARGET_TYPES[0]}
    autoninja -C "$CHROMIUM_OUTPUT_DIR" ${TARGET_TYPES[1]}

    [[ -n "$OUTPUT_DIR" ]] \
        && mkdir -p "$OUTPUT_DIR" \
        && cp -f "$CHROMIUM_OUTPUT_DIR/apks/ChromePublic.apk" "$OUTPUT_DIR" \
        && cp -f "$CHROMIUM_OUTPUT_DIR/apks/SystemWebView.apk" "$OUTPUT_DIR"

}

_setopts () {
    # Cast args to array for easier parsing
    local args_arr=()

    for arg in $*; do
        [[ ! $arg =~ (--[a-z|-]+)= ]] \
            && args_arr+=("$arg") \
            && continue

        local arg_key
        local arg_value

        arg_key=$(echo "$arg" | sed -E 's/=.+//')
        arg_value=$(echo "$arg" | sed -E "s/$arg_key=//")

        args_arr+=("$arg_key")
        args_arr+=("$arg_value")
    done;

    # Iterate options and assign var values to CLI args
    for opt in "${opts[@]}"; do
        [[ $opt =~ '-h, --help' ]] \
            && continue

        local opt_arr=($(echo "$opt" \
            | sed -E "s/\s*\|.+//g" \
            | sed -E "s/=<.+>//g" \
            | tr ", " "\n"))

        [[ ${#opt_arr[@]} != 2 ]] \
            && opt_arr+=("${opt_arr[0]}")

        local opt_var
        local opt_var_types
        local arg_next
        local idx=0

        opt_var=$(echo "${opt_arr[1]}" \
            | sed -E "s/^--//g" \
            | sed -E "s/\W/_/g" \
            | tr '[a-z]' '[A-Z]')

        opt_var_types=${opt_var}_TYPES[@]

        for arg in "${args_arr[@]}"; do
            case $arg in
                ${opt_arr[0]}|${opt_arr[1]})
                    arg_next=${args_arr[$idx + 1]:-}

                    # Boolean opts
                    [[ ! $opt =~ \=\<.+\> ]] \
                        && export "$opt_var=1" \
                        && continue

                    # Flags that need to fallback to default values
                    [[ $opt =~ \=\<.+:\=.+\> ]] \
                            && [[ ${arg_next::1} == '-' || ! $arg_next ]] \
                        && export "$opt_var=$(echo "$opt" \
                            | sed -E "s/\s*\|.+//g" \
                            | sed -E "s/.+\<.+:\=([^\>]+).+/\1/")" \
                        && continue

                    # Flags with custom or type-specific values
                    [[ ! ${!opt_var_types:-} ]] \
                            || [[ $(printf "%s\n" ${!opt_var_types} \
                                | grep -n "^${args_arr[$idx + 1]}$") ]] \
                        && export "$opt_var=${args_arr[$idx + 1]}"
                    ;;
            esac

            idx=$(( "$idx" + 1 ))
        done
    done
}

_localpatches () {
    local patches_dir_msg
    local patches_dir_abspath
    local patches_dirname

    # No patches directory set, return
    [[ ! $PATCHES_DIR ]] \
        && return

    patches_dir_msg="Patches directory \"$PATCHES_DIR\" not found. Skipping"

    # Patches directory absolute path and exists, return
    if [[ $PATCHES_DIR = /* ]]; then
        [[ ! -d $PATCHES_DIR ]] \
            && echo "$patches_dir_msg" \
            && export PATCHES_DIR=
        return
    fi

    # Patches directory relative, update to absolute
    patches_dir_abspath=$(cd "$( dirname "$PATCHES_DIR" )" && pwd)
    patches_dirname=$(basename $PATCHES_DIR)

    [[ ! -d "$patches_dir_abspath/$patches_dirname" ]] \
        && echo "$patches_dir_msg" \
        && export PATCHES_DIR= \
        && return

    export PATCHES_DIR="$patches_dir_abspath/$patches_dirname"
}

_localbin () {
    local protobuf_repo
    local protoc_javalite_bin

    mkdir -p "$CWD/.bin"

    # Depot Tools
    [[ ! -d $CWD/.bin/depot_tools ]] \
        && cd "$CWD/.bin" \
        && echo "Fetching Depot Tools" \
        && git clone -q https://chromium.googlesource.com/chromium/tools/depot_tools.git

    cd "$CWD/.bin/depot_tools"
    git checkout main -q
    git pull -q

    # Update PATH
    export PATH=$CWD/.bin:$CWD/.bin/depot_tools:$PATH
    export PYTHONPATH="$CWD/.bin/depot_tools/third_party:$PYTHONPATH"
}

_getcmds () {
    echo $(typeset -f \
        | awk '/ \(\) $/ && !/^(main) / {print $1}' \
        | sed -E "s/(_.+\s*)//g")
}

_help () {
cat <<HEREDOC
Usage: ${0} [command...] [options...]

Where optional [command] is one of:
  $(_getcmds | sed -E "s/\s/, /g")

If no [command] is set, the default command sequence will be executed:
$(printf "  - %s\n" "${DEFAULTS[@]}")

Options:$(printf "\n  %s\n" "${opts[@]}" \
    | sed -E "s/(\<.+):\=[^\>]*(>)/\1\2/g" \
    | sed -E "s/\s\|\s/\n    /g" \
    | sed -E "s/\.\s/.\n    /g")

HEREDOC
}

main () {
    # Help Menu
    [[ $(echo "$@") == -h ]] || [[ $(echo "$@") == --help ]] \
        && _help \
        && return

    # Set Options
    _setopts "$@"

    # Setup custom patches dir
    _localpatches

    # Setup Local bin
    _localbin

    # Detect if 1st param of args is a valid function
    if [[ ${1:-} ]] && [[ $(_getcmds) =~ $1 ]]; then
        [[ $1 != 'set-revision' ]] && [[ $1 != 'clean' ]] \
            && set-revision
        $1
        return
    fi

    # No command detected, run default sequence
    for cmd in "${DEFAULTS[@]}"; do
        eval "$cmd"
    done
}

# Entry Function
main "$@"
